### ISSUE TITLE
Unexpected Behavior

### ISSUE THREAD

**Issue by timscott** [glg-public/gds-cc-screamer#84]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.p01/pull/46)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.p01/blob/a81591e528ab15c9dbbaf6caea46e635aa1382d5/message-index-events/secrets.json#L24)

# Result Contents

## ⚠️ Secret Could Not Be Found
- The following secret could not be found: `prod/SCHEDULING_SUMO_LOGIC_TOKEN`

**Comment by shawnrushefsky** [comment]
This occurred because deployinator uses a cache, so the list of available secrets can be up to 30 minutes stale. This can be corrected by calling `https://deploy.glgresearch.com/deployinator/enumerate/secrets?bust=true` to refresh the cache. Once the cache is refreshed, re-running the github action will achieve the expected behavior.
